### ISSUE TITLE
TypeError for track_audio_features when track doesn't have features

### ISSUE THREAD

**Issue by csparker247** [felix-hilden/spotipy#99]
I'm iterating over large lists of Spotify IDs in chunks of 50 ids and requesting the audio features for those tracks. I'm having an issue where the `tracks_audio_features` call raises a TypeError when one of the included tracks doesn't have any audio features.

```python
spotify.tracks_audio_features(['7wpxbJPkrdnC40hwr4FPUa'])
```
results in the following error:
```
Traceback (most recent call last):
  File "get_track_features.py", line 52, in <module>
    spotify.tracks_audio_features(['7wpxbJPkrdnC40hwr4FPUa'])
  File "/Users/seth/source/spotipy/spotipy/client/track.py", line 90, in tracks_audio_features
    return ModelList(AudioFeatures(**a) for a in json['audio_features'])
  File "/Users/seth/source/spotipy/spotipy/client/track.py", line 90, in <genexpr>
    return ModelList(AudioFeatures(**a) for a in json['audio_features'])
TypeError: type object argument after ** must be a mapping, not NoneType
```

Asking for the problematic track individually with `tracks_audio_features` confirms there's nothing to get:
```
Traceback (most recent call last):
  File "get_track_features.py", line 53, in <module>
    analysis = spotify.track_audio_features('7wpxbJPkrdnC40hwr4FPUa')
  File "/Users/seth/source/spotipy/spotipy/client/track.py", line 77, in track_audio_features
    json = self._get('audio-features/' + track_id)
  File "/Users/seth/source/spotipy/spotipy/client/base.py", line 139, in _get
    return self._request('GET', url, payload=payload, params=params)
  File "/Users/seth/source/spotipy/spotipy/client/base.py", line 135, in _request
    response = self._send(request)
  File "/Users/seth/source/spotipy/spotipy/client/base.py", line 122, in _send
    raise HTTPError(error_str, request=request, response=response)
requests.exceptions.HTTPError: Error in https://api.spotify.com/v1/audio-features/7wpxbJPkrdnC40hwr4FPUa:
404: analysis not found
```

In the general case, I'm not sure this is recoverable without modifying the spotipy source.

**Comment by felix-hilden** [comment]
Thanks for the report! I'll add a `None` check for that.
